var itKeywords = [
  "Systems and Computing Engineering",
  "Computer engineering",
  "Computer sciences",
  "Software development and programming",
  "WordPress",
  "Microsoft Dynamics",
  "Solution Orientation",
  "Cloud computing management",
  "AWS (Amazon Web Services)",
  "Heroku",
  "Android studio",
  "Atom",
  "Git",
  "NPM",
  "Sublime",
  "Vim",
  "Xamarin",
  "Xcode",
  "Database Administration",
  "Database Management",
  "Elasticsearch",
  "SQLite",
  "Tableau",
  "Final Cut Pro",
  "iMovie",
  "Sony Vegas",
  "Sharepoint",
  "Slack",
  "Zoho",
  "Android",
  "iOS",
  "UNIX",
  "Windows",
  "MS DOS",
  "HTML",
  "Java",
  "ASP",
  "Javascript",
  "SQL",
  "C#",
  "Visual Basic",
  "PHP",
  "Python",
  "Ajax",
  "CSS",
  "Ruby",
  "HTML 5",
  "Objective C",
  "Assembly",
  "Unix shell scripting",
  "Network management and data transmission",
  "TCP/IP",
  "LAN (local area network)",
  "WAN (wide area network)",
  "Voice - IP Telephony (VoIP)",
  "Network Design",
  "Network security",
  "Operating systems",
  "MacOS",
  "Android",
  "iOS",
  "ERP",
  "UI design",
  "UX design",
  "SAP",
  "Salesforce",
  "Oracle",
  "Microsoft Access",
  "DB/2",
  "Microsoft SQL Server",
  "MySQL",
  "NoSQL",
  "MongoDB",
  "Node.js",
  "Django",
  "Laravel",
  "Object Oriented Programming",
];
var financeKeywords = [
  "Accounting",
  "Finance",
  "Business administration",
  "Economics",
  "Financial management",
  "Banking",
  "Supply Chain management",
  "Controlling",
  "Business Intelligence",
  "Market Research",
  "Risk Management",
  "Search Engine Optimization (SEO)",
  "Consulting",
  "Negotiation",
  "Public Relations",
  "Technical Support",
];
var businessAdminKeywords = [
  "Business administration",
  "Entrepreneurship",
  "International Trade",
  "Logistics",
  "Public administration",
  "Human Resources",
  "International relations",
  "Sales",
  "Leadership",
  "Team Management",
  "Project Management",
  "Presentation skills",
  "Language Teaching",
  "Organisational Management",
  "Training",
];
var marketingKeywords = [
  "Marketing",
  "Digital Marketing",
  "Content Marketing",
  "Media Planning",
  "Market Research",
  "Search Engine Optimization (SEO)",
  "Social Media Management",
  "Public Relations",
  "Adobe After Effects",
  "Adobe Audition",
  "Adobe Bridge",
  "Adobe Dreamweaver",
  "Adobe InDesign",
  "Adobe Lightroom",
  "Adobe Premiere Pro",
  "Advertising",
  "Presentation skills",
  "Language Teaching",
  "Training",
  "Creativity",
  "Graphic design",
  "Design",
  "Media Arts",
  "Strategic Planning",
  "Content Strategy",
];
var teachingKeywords = [
  "Language Teaching",
  "Literature",
  "Education",
  "Languages",
];
var otherKeywords = [
  "Other",
  "Law",
  "Communication & journalism",
  "Arts",
  "Anthropology",
  "Internet usage",
  "Microsoft Dynamics",
  "AIESEC Leadership qualities",
  "Empowerment of others",
  "Self Awareness",
  "Solution Orientation",
  "World citizenship",
  "Heroku",
  "Dropbox",
  "Google Drive",
  "Keynote",
  "Microsoft Excel",
  "Microsoft Powerpoint",
  "Microsoft Word",
  "Pages",
  "Filming",
  "Final Cut Pro",
  "Image editing",
  "iMovie",
  "Sony Vegas",
  "Sharepoint",
  "Slack",
  "Workplace",
  "Zoho",
  "Controlling",
  "Supply Chain management",
  "Blogging",
  "Consulting",
  "Event Planning",
  "Facilitation",
  "Handling Pressure",
  "HR induction",
  "Research",
  "Technical Support",
  "Work Ethic",
  "Writing",
  "Computer aided technical design",
  "Client servicing",
  "Mac usage",
  "Windows PC usage",
];
var engineeringDictionary = [
  "Bioengineering",
  "Petroleum Engineering",
  "Aerospace engineering",
  "Automotive engineering",
  "Chemical engineering",
  "Civil engineering",
  "Electrical engineering",
  "Environmental engineering",
  "Industrial engineering",
  "Mechanical engineering",
  "Material engineering",
];
